### ISSUE TITLE
Feat: allow github OAuth

### ISSUE THREAD

**Issue by marceloavf** [marceloavf/github-tools-vsts#17]
Allow integration with OAuth authentication, not just Personal Access Token.

- Return message about endpoint with token
- Add to documentation the related issue as known issues or/and how connection should be

```
✅ Accept: scheme: 'PersonalAccessToken' 
✅ Accept: scheme: 'OAuth' 
```
#### Basic return
```
{
  parameters: 
     {
        accessToken: '********'
      },
  scheme: 'PersonalAccessToken'
}
```
#### Case 1
```
Error: missing required options: token
```

#### Case 2
```
Error status: 401  response body:{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
```

---

References: 
[Code 1](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzureResourceGroupDeployment/models/DeployAzureRG.ts#L55)
[Code 2](https://github.com/Microsoft/vsts-extension-build-release-tasks/blob/master/BuildTasks/Common/Common.ts#L266)
[Code 3](https://github.com/Microsoft/vsts-tasks/issues/6271)

Related to #16

**Comment by onovotny** [comment]
Is it possible to use an OAuth endpoint instead of returning an error? What's the issue?

**Comment by marceloavf** [comment]
@onovotny, the library `publish-release` that's used to do all comunication with GitHub API require a token to authenticate it, I would have to investigate what OAuth token return and send it to `publish-release` instead of the normal token in the code below.

PR are welcome! 🙌 

https://github.com/marceloavf/github-tools-vsts/blob/24d167eff604393c38a3ac06db84ab523cfe7d98/Src/GithubReleasePublish/githubReleasePublish.js#L13-L14
https://github.com/remixz/publish-release/blob/master/index.js#L76

**Comment by onovotny** [comment]
I believe that it's as easy as changing line 76 there from ` 'Authorization': 'token ' + opts.token,` to ` 'Authorization': 'Bearer ' + opts.token,`, 

Plus whatever overload/config it'd need to support both methods. Like PAT, it's just another type of Authorization header.

**Comment by marceloavf** [comment]
I didn't notice that @onovotny, thanks for the details, so `Bearer` can support both parameters?

I'll try to dig the documentation of EndpointAuthorization to see if it return more parameters, but I think it returns in other prop as you can see in #16

**Comment by tomkerkhove** [comment]
Would like this as well 👍

**Comment by tomkerkhove** [comment]
Tested and verified ✔️ Thanks @marceloavf 🎉
