### ISSUE TITLE
Asset upload:  Error: write EPIPE

### ISSUE THREAD

**Issue by FutureGUIs** [marceloavf/github-tools-vsts#21]
Before opening an issue please [read this](https://github.com/marceloavf/github-tools-vsts/wiki/How-to-Report-an-issue).

# Are you reporting a bug or a feature request ?
* [X] Bug
* [ ] Feature request

# Description

Pretty regularly I get EPIPE issues during uploads of assets to GitHub.

# Expected behavior

Uploads succeed all the time.

# Reproduction

No reliable way to reproduce

Debug trace
```
2018-03-21T20:27:49.5501990Z Uploading asset xxx-v0.0.0-AppCenter.apk - 1% - 256.0 KB/s
2018-03-21T20:27:49.6586010Z Uploading asset xxx-v0.0.0-AppCenter.apk - 8% - 1.2 MB/s
2018-03-21T20:27:49.6826550Z ##[debug]task result: Failed
2018-03-21T20:27:49.6950460Z ##[error]An error occured, log returned: 
Error: write EPIPE
2018-03-21T20:27:49.6988110Z ##[debug]Processed: ##vso[task.issue type=error;]An error occured, log returned: %0AError: write EPIPE
2018-03-21T20:27:49.7017520Z ##[debug]Processed: ##vso[task.complete result=Failed;]An error occured, log returned: %0AError: write EPIPE
```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository*

# System information

**VSTS or TFS:**
* [X] VSTS
* [ ] TFS

**Agent:**
* [X] Hosted
* [ ] Custom

**OS:**
* [ ] Windows
* [X] Mac
* [ ] Linux

**Node version:**
9.8

**Comment by marceloavf** [comment]
Hi @FutureGUIs,

Have you tried node version `8.10` ?
Could you confirm if the asset appears broken into the release on GitHub, with a red icon next to it?

Thanks for the feedback!

**Comment by FutureGUIs** [comment]
The asset does not appear to be broken, it leaves the old file there.  I'll set my vsts to use node 8 and let that run for a while to see if I still hit that error.

**Comment by FutureGUIs** [comment]
Getting the same EPIPE errors using node 8.10 ...

**Comment by marceloavf** [comment]
Ok @FutureGUIs, I'll investigate this futher, can you please tell me the size of this .apk that you are sending there?
It only happens when there is already an old asset with the same name or when you are creating a new one?

Thanks!

**Comment by FutureGUIs** [comment]
they range in size from 2MB to 13MB, I've only seen it happen on the larger ones.  And I haven't noticed on brand new ones either

**Comment by marceloavf** [comment]
Nice, so it only happens when reusing and replacing an asset?
Can you please show me your `Advanced` configs? only the check box ones, please.

Thanks!

**Comment by FutureGUIs** [comment]
only "Reuse Release" and "Edit Release" checked

**Comment by marceloavf** [comment]
This error seems to be related to the core `publish-release` package when it create a request to start the upload and find a duplicated asset, after that it seems to lose the stream progress of this request and give a random EPIPE error when it retries to upload. I still need to investigate more, I'm not sure yet.

Could you confirm if it only happens after deleting an old asset?

Thanks!

**Comment by FutureGUIs** [comment]
Correct after deleting the old one

**Comment by marceloavf** [comment]
Since we can't replicate this and many others problems seems to be from Azure DevOps internals, I'll close this one, but feel free to reopen it if happens again.
