### ISSUE TITLE
Document manifest approach

### ISSUE THREAD

**Issue by tomkerkhove** [marceloavf/github-tools-vsts#26]
Would be good to have documentation on what the manifest looks like and how we can use this

**Comment by marceloavf** [comment]
Some tests can give an example of how it works, but would be nice to document it in wiki or some .md too.

https://github.com/marceloavf/github-tools-vsts/blob/eb9ae773407aeb5aaaaf275267dab9ffddd02c2a/Tests/readManifest.test.js#L4-L8

https://github.com/marceloavf/github-tools-vsts/blob/eb9ae773407aeb5aaaaf275267dab9ffddd02c2a/Tests/fixtures/manifest.json#L1-L7
