### ISSUE TITLE
Tag needs to support variables

### ISSUE THREAD

**Issue by atrauzzi** [marceloavf/github-tools-vsts#33]
![image](https://user-images.githubusercontent.com/115199/46428792-846aeb00-c70a-11e8-8ec1-cf06a38166fd.png)

I have my own version that I generate during builds.  That version number needs to be the value I use for my tag when I reach out to source control.  I don't have a `package.json` and I don't want it prepended with a `v`.

**Comment by marceloavf** [comment]
Hey @atrauzzi, thanks for the feedback.

Do you create this `VERSION` variable with another task or it is set in variables tab ?
It is strange since this input do support build variable, which in the case are the same thing.

**Comment by marceloavf** [comment]
I just created a test build with powershell task that create variable the same way you said

```powershell
Write-Host "##vso[task.setvariable variable=VersionNumber;]1.0.0"
```

Then I included it in the GitHub Release task

![image](https://user-images.githubusercontent.com/5435657/46438023-2a325000-c733-11e8-945c-055cba4b7af1.png)

After finishing the build it set the same version in the release that I created 😞 

![image](https://user-images.githubusercontent.com/5435657/46438122-6b2a6480-c733-11e8-9530-d5672cb9dd04.png)

---

Could you provide more information about something you are doing differently ?

**Comment by marceloavf** [comment]
Any update on this @atrauzzi ?
