### ISSUE TITLE
New lines in release notes

### ISSUE THREAD

**Issue by josesimoes** [marceloavf/github-tools-vsts#37]
## Question
How to add new lines in release notes in yaml?

**Description**
How can use "\n" in the release notes when configuring the task in yaml?

I've tried:

`'Check the [changelog]\n`

`'Check the [changelog]/\n`

`'Check the [changelog]\\n`

and I always end up with this: 
![image](https://user-images.githubusercontent.com/1881520/48943566-88053c00-ef1b-11e8-9f47-39e9e0e6039f.png)

What's the proper way to escape this? Or could it be that something is not being handled properly when sending this to GitHub?

Thanks! 😄

**Comment by marceloavf** [comment]
Hey @josesimoes, thank you for the feedback.

Release notes on GitHub are written in markdown, so you can use tag `<br>` to jump line.
I think double break line works too, but it was not tested.

---

For example:
![image](https://user-images.githubusercontent.com/5435657/48948428-863b7880-ef1b-11e8-9930-dfeb72e1866b.png)
or
![image](https://user-images.githubusercontent.com/5435657/48948381-660bb980-ef1b-11e8-97ea-0c8a37d4b4e5.png)

---

Please, let me know if it works.
Thank you again!

**Comment by josesimoes** [comment]
Double break lines was was I was trying to use, without success. I've used HTML markdown with <br> as you've suggested and it's working. 

Obrigado e parabéns pelo excelente trabalho nesse componente! 😉  👏

**Comment by marceloavf** [comment]
Glad that it worked @josesimoes.

Muito obrigado!
