### ISSUE TITLE
Link GitHub Release to Tag

### ISSUE THREAD

**Issue by jeanfrancoislarente** [marceloavf/github-tools-vsts#38]
## Question
Fantastic extension by the way!
When I publish my release, the <version_no> release seems to get created 'unlinked' from the tag. Instead it creates the release with 'releases/tag/untagged-13b8ac56b9b557bbbade' as the name.

I'd like to know if it's possible (and if so, how) to create a release and have it linked to a tag at the same time.

**Description**
My task yaml: (major, minor, patch resolves to 9.1.0.1 for example)

```
- task: marcelo-formentao.github-tools.github-release-publish-task.GitHubReleasePublish@1
  displayName: 'Create GitHub Release'
  inputs:
    githubEndpoint: 'GitHub connection 1'

    githubRepository: myrepo

    githubTag: '$(major).$(minor).$(patch)'

    githubReleaseTitle: '$(major).$(minor).$(patch)'

    githubReleasePrerelease: true

    githubReleaseAsset: |
     $(Build.ArtifactStagingDirectory)/9.1.0/XPSingle/assets/WDP/*

    githubEditRelease: true

    isPreRelease: true```

The result is a tag (good) and a release (good) but they're not linked together in GitHub (not-so-good) :)

Thanks in advance @marceloavf !

**Comment by marceloavf** [comment]
Closed due to no response.
